### ISSUE TITLE
Unknown identifier should tell you which identifier

### ISSUE THREAD

**Issue by kavigupta** [rahularya50/scheme_interpreter_personal#15]
Currently it doesn't which makes it hard to glance at your code and fix the error.

**Comment by rahularya50** [comment]
Doesn't it?

![image](https://user-images.githubusercontent.com/18374604/52679109-dad20c80-2ee8-11e9-9a87-05a94ab4b475.png)

If you mean the error in OKPy, then ~~I think that's what OKPy's Scheme interpreter does, not my interpreter.~~ it seems to be a bug in how I parse the OKPy output.

Ideally, I'd redo how I parse the OKPy output entirely, since currently I just redirect standard out and try to parse the text. Do you know if the client has some sort of API that I can use to get the test results?

**Comment by kavigupta** [comment]
I'll look into it. There may be a better way.

**Comment by kavigupta** [comment]
Resolved by https://github.com/Cal-CS-61A-Staff/scheme_interpreter_personal/pull/21
