### ISSUE TITLE
Infinite loops take up a ridiculous amount of memory

### ISSUE THREAD

**Issue by kavigupta** [rahularya50/scheme_interpreter_personal#25]
If I run

```
(define (loop) (loop))
(loop)
```

then it uses a ridiculous amount of memory

![image](https://user-images.githubusercontent.com/3214932/53138131-1482c300-353a-11e9-9b8a-0be870e44f28.png)

this linearly increases, which means it ate 16% of my 8GB memory in 22s, which means it's eating 58 MB/s.

Either it should error with a max recursion depth or it should tail recurse

**Comment by rahularya50** [comment]
The interpreter is tail recursive, which is why we aren't getting a max recursion depth error.

The issue is that the debugger works by storing each step of execution, which takes space linear in the runtime. I see a couple possible solutions to this:
  * One is to error with a max recursion depth. Issue is that this could affect actual tail recursive problems, though of course we could always just increase the recursion depth so it doesn't affect anything from HWs.
 * Another is to throw an exception based on memory usage. This would also ensure that programs with lower recursion depth but which make multiple recursive calls (e.g. `(define (loop) (loop) (loop))`) will also not consume large amounts of memory.
 * Finally, we could just stop the debugger for very long programs and return a warning to the user. This is the solution I'm leaning towards. And I think I should be able to allow the first few steps of debugging to return to the user, so they can see what is causing the infinite loop. To do so, we'd need to
    - [ ] Implement a warning in the GUI that the debugger is disabled
    - [ ] Disable logging server-side based on memory consumption
    - [ ] Ensure that subsequent interaction with the console can still be debugged, even when previous code timed out.
    - [ ] Disable the logging of the call stack at some point, since super long error tracebacks are meaningless anyway? But then the memory usage of the stack isn't significant anyway.
    - [ ] Possibly raise some sort of warning in the console, indicating that the debugger had to stop logging at some point? Maybe provide statistics?

Also, the current behavior can cause further issues if the program is just very long but does ultimately terminate, since when we try to send the results back to the browser, the page runs out of memory and crashes.

**Comment by kavigupta** [comment]
Fixed.
